// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileDto = {
  id: number;
  confluence_id: number;
  created_at: number;
  updated_at: number;
  resource_token: string;
  transform_script?: string;
  transform_script_transpiled?: string;
};
