FROM oven/bun:1-alpine
WORKDIR /injector
COPY ./apps/outposts-web-host/inject.ts ./inject.ts
COPY ./apps/outposts-web-host/config-projection-bootstrap.ts ./config-projection-bootstrap.ts
COPY ./dist/apps/outposts-web /app
CMD ["bun", "run", "inject.ts"]
